name: Bygg og deploy
on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '.gitignore'
      - '.editorconfig'
      - 'LICENCE'
      - 'CODEOWNERS'

jobs:
  build-app:
    name: Build
    uses: navikt/fp-gha-workflows/.github/workflows/build-app-frontend-npm.yml@main
    with:
      node-version: '16.19.0' # TODO: Bytt til samme versjon som DockerFile (16.19.0 ble brukt før i bygg)
      build-image: ${{ github.ref_name == 'master' }} # default: true
      push-image: ${{ github.ref_name == 'master' }} # default: false
    secrets: inherit

  create-issue:
    name: Issues
    if: github.ref_name == 'master'
    needs: build-app
    uses: navikt/fp-gha-workflows/.github/workflows/issues.yml@main
    with:
      build-version: ${{ needs.build-app.outputs.build-version }}
    secrets: inherit

  promote:
    name: Deploy til dev
    if: github.ref_name == 'master'
    needs: [ build-app, create-issue ]
    uses: navikt/fp-gha-workflows/.github/workflows/promote.yml@main
    with:
      issue-number: ${{ needs.create-issue.outputs.issue-number }}
      cluster: dev-gcp
    secrets: inherit

  snyk:
     name: Snyk
     needs: build-app
     uses: navikt/fp-gha-workflows/.github/workflows/snyk-frontend.yml@main
     with:
       upload-sarif: ${{ github.ref_name == 'master' }}
     secrets: inherit
